= Spring Boot for Apache Geode & Pivotal GemFire Reference Guide
John Blum;
:revnumber: {version}
:revdate: {localdate}
:doctype: book
:toc:
:toclevels: 4
:!toc-placement:
:source-highlighter: prettify
:numbered:
:icons: font
:hide-uri-scheme:
:apache-geode-version: 16
:apache-geode-docs: http://geode.apache.org/docs/guide/{apache-geode-version}
:apache-geode-javadoc: http://geode.apache.org/releases/latest/javadoc
:spring-boot-docs: https://docs.spring.io/spring-boot/docs/current/reference
:spring-boot-docs-html: {spring-boot-docs}/htmlsingle
:spring-boot-javadoc: https://docs.spring.io/spring-boot/docs/current/api
:spring-data-commons-docs: https://docs.spring.io/spring-data/commons/docs/current/reference
:spring-data-commons-docs-html: {spring-data-commons-docs}/html
:spring-data-commons-javadoc: https://docs.spring.io/spring-data/commons/docs/current/api
:spring-data-geode-docs: https://docs.spring.io/spring-data/geode/docs/current/reference
:spring-data-geode-docs-html: {spring-data-geode-docs}/html
:spring-data-geode-javadoc: https://docs.spring.io/spring-data/geode/docs/current/api
:spring-data-gemfire-docs: https://docs.spring.io/spring-data/gemfire/docs/current/reference
:spring-data-gemfire-docs-html: {spring-data-gemfire-docs}/html
:spring-data-gemfire-javadoc: https://docs.spring.io/spring-data/gemfire/docs/current/api
:spring-framework-docs: https://docs.spring.io/spring/docs/current/spring-framework-reference
:spring-framework-javadoc: https://docs.spring.io/spring/docs/current/javadoc-api
:wikipedia-docs: https://en.wikipedia.org/wiki

(C) 2018 The original authors.

NOTE: Copies of this document may be made for your own use and for distribution to others provided that you do not
charge any fee for such copies and further provided that each copy contains this Copyright Notice
whether distributed in print or electronically.

toc::[]

[[abstract]]
Welcome to _Spring Boot for Apache Geode & Pivotal GemFire_.

Spring Boot for Apache Geode & Pivotal GemFire provides the convenience of Spring Boot's _convention over configuration_
approach using _auto-configuration_ with the Spring Framework's powerful abstractions and programming model to simplify
the development of Apache Geode or Pivotal GemFire applications in a Spring enabled context.

Secondarily, Spring Boot for Apache Geode/Pivotal GemFire strives to provide developers with a consistent experience
when building and running Spring-powered, Apache Geode/Pivotal GemFire applications, whether a developer's Spring Boot
applications are running locally, or in a managed environment, such as https://pivotal.io/platform[Pivotal CloudFoundry] (PCF).

This project is a continuation and logical extension of the work that began in Spring Data for Apache Geode & Pivotal GemFire
with the relatively new {spring-data-geode-docs-html}/#bootstrap-annotation-config[Annotation-based Configuration Model]
and the goals set forth with that: _enable application developers to *get up and running* as *quickly* and as *easily*
as possible_.  In fact, Spring Boot for Apache Geode/Pivotal GemFire builds on the very
{spring-data-geode-docs-html}/#bootstrap-annotation-config[foundation]
built into Spring Data for Apache Geode/Pivotal GemFire (SDG) as of the Spring Data *Kay* _Release Train_.

[[introduction]]
== Introduction

Spring Boot for Apache Geode & Pivotal GemFire automatically applies _auto-configuration_ for several key
application concerns, or _Use Cases_, including, but not limited to:

* _Look-Aside Caching_, using either Apache Geode or Pivotal GemFire as the caching provider in
{spring-framework-docs}/integration.html#cache[Spring's Cache Abstraction].
* {wikipedia-docs}/System_of_record[_System of Record_ (SOR)], persisting application state in Apache Geode
or Pivotal GemFire consistently and reliably using {spring-data-commons-docs-html}/#repositories[Spring Data Repositories].
* _Distributed Computations_, run with Apache Geode/Pivotal GemFire's
{apache-geode-docs}/developing/function_exec/chapter_overview.html[Function framework],
conveniently implemented and executed with Spring Data for Apache Geode/Pivotal GemFire
{spring-data-geode-docs-html}/#function-annotations[POJO, annotation-based Function Executions & Implementations].
* _Continuous Queries_, expressing interests in a stream of events, where applications are able to react to and process
changes to data in near real-time using Apache Geode/Pivotal GemFire {apache-geode-docs}/developing/continuous_querying/chapter_overview.html[Continuous Query (CQ)].
Process handlers can be defined as simple Message-Driven POJOs (MDP) using Spring's {spring-framework-docs}/integration.html#jms-mdp[Message Listener Container],
which is {spring-data-geode-docs-html}/#bootstrap-annotation-config-continuous-queries[configurable] and {spring-data-geode-docs-html}/#apis:continuous-query[implemented]
in Spring Data for Apache Geode/Pivotal GemFire CQ support.
* _Data Serialization_ with Apache Geode/Pivotal GemFire {apache-geode-docs}/developing/data_serialization/gemfire_pdx_serialization.html[PDX]
for which Spring Data for Apache Geode/Pivotal GemFire provides first-class {spring-data-geode-docs-html}/#bootstrap-annotation-config-pdx[configuration]
and {spring-data-geode-docs-html}/#mapping.pdx-serializer[support].
* _Security_, encompassing all aspects of the term, including
{apache-geode-docs}/managing/security/authentication_overview.html[Authentication] / {apache-geode-docs}/managing/security/authorization_overview.html[Authorization]
as well as Transport Layer Security (TLS) using Apache Geode/Pivotal GemFire's {apache-geode-docs}/managing/security/ssl_overview.html[Secure Socket Layer (SSL)].
And, once again, Spring Data for Apache Geode/Pivotal GemFire has you covered with both
{spring-data-geode-docs-html}/#bootstrap-annotation-config-security[Auth] and {spring-data-geode-docs-html}/#bootstrap-annotation-config-ssl[SSL].

While Spring Data for Apache Geode & Pivotal GemFire offers a simple, convenient and declarative approach for
configuring all these really powerful Apache Geode/Pivotal GemFire features, Spring Boot for Apache Geode
& Pivotal Gemfire makes this even easier to do as we will explore throughout this Reference Guide.

[[getting-started]]
== Getting Started

In order to be as effective as possible and productive with Spring Boot for Apache Geode/Pivotal GemFire, it is helpful
to understand the foundation on which this project was built.

Of course, our story begins with the core Spring Framework and specifically the foundation laid down by
the Spring container's {spring-framework-docs}/core.html#spring-core[core technologies and concepts].

Then, our journey continues with the extensions built into Spring Data for Apache Geode & Pivotal GemFire (SDG) to truly
simplify the development of Apache Geode & Pivotal GemFire applications in a Spring context, using Spring's powerful
and highly consistent programming model.

This part of the story was greatly enhanced in Spring Data *Kay*, with SDG's new
{spring-data-geode-docs-html}/#bootstrap-annotation-config[annotation-based configuration model].
Though this new configuration approach using annotations provides sensible defaults out-of-the-box, its use
is also very explicit and it assumes nothing.  That is, you still must tell SDG what you want.

Next, we venture into Spring Boot and all of its wonderfully expressive and highly opinionated "_convention over configuration_"
approach for getting the most out of your Spring, Apache Geode or Pivotal GemFire based applications in the quickest/easiest way
possible.  We accomplish this by combining Spring Data for Apache Geode/Pivotal GemFire's
{spring-data-geode-docs-html}/#bootstrap-annotation-config[annotation-based configuration] with Spring Boot's
{spring-boot-docs-html}/#using-boot-auto-configuration[auto-configuration] to get you up and running even faster
and more reliably so that you are productive from the start.

As such, it would be pertinent to begin your Spring Boot education {spring-boot-docs-html}/#getting-started[here].

Finally, we arrive at Spring Boot for Apache Geode & Pivotal GemFire.

[[maven-gradle]]
== Using Spring Boot for Apache Geode or Pivotal GemFire

To use Spring Boot for Apache Geode, declare the `spring-geode-starter` on your application classpath:

.Maven
[source,xml]
[subs="verbatim,attributes"]
----
<dependencies>
    <dependency>
        <groupId>org.springframework.geode</groupId>
        <artifactId>spring-geode-starter</artifactId>
        <version>{spring-boot-data-geode-version}</version>
    </dependency>
</dependencies
----

.Grade
[source,groovy]
[subs="verbatim,attributes"]
----
compile 'org.springframework.geode:spring-geode-starter:{spring-boot-data-geode-version}'
----

TIP: To use Pivotal GemFire in place of Apache Geode, simply change the `artifactId` from `spring-geode-starter`
to `spring-gemfire-starter`.

ifeval::["{version-snapshot}" == "true"]
Since we are using a SNAPSHOT version, we need to add the _Spring_ Snapshot Maven Repository.
If you are using _Maven_, include the following `repository` declaration in your `pom.xml`:

.Maven
[source,xml]
----
<repositories>
    <repository>
        <id>spring-snapshot</id>
        <url>https://repo.spring.io/libs-snapshot</url>
    </repository>
</repositories>
----

If you are using _Gradle_, include the following `repository` declaration in your `build.gradle`:

.Gradle
[source,gradle]
----
repositories {
    maven { url: 'https://repo.spring.io/libs-snapshot' }
}
----
endif::[]

ifeval::["{version-milestone}" == "true"]
Since we are using a Milestone version, we need to add the _Spring_ Milestone Maven Repository.
If you are using _Maven_, include the following `repository` declaration in your `pom.xml`:

.Maven
[source,xml]
----
<repositories>
    <repository>
        <id>spring-milestone</id>
        <url>https://repo.spring.io/libs-milestone</url>
    </repository>
</repositories>
----

If you are using _Gradle_, include the following `repository` declaration in your `build.gradle`:

.Gradle
[source,gradle]
----
repositories {
    maven { url: 'https://repo.spring.io/libs-milestone' }
}
endif::[]

include::clientcache-applications.adoc[]
include::caching.adoc[]
include::repositories.adoc[]
include::functions.adoc[]
